import { boolean, integer, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })

export const brands = pgTable('brands', { id: serial('id').primaryKey(), userId: text('userId').notNull(), name: text('name').notNull(), tone: text('tone'), values: text('values'), guidelines: text('guidelines'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const contentPieces = pgTable('content_pieces', { id: serial('id').primaryKey(), userId: text('userId').notNull(), brandId: integer('brandId'), title: text('title').notNull(), type: text('type').notNull(), status: text('status').notNull().default('draft'), content: text('content'), imageUrl: text('imageUrl'), scheduledAt: timestamp('scheduledAt'), generatedVia: text('generatedVia'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const analytics = pgTable('analytics', { id: serial('id').primaryKey(), userId: text('userId').notNull(), contentId: integer('contentId'), views: integer('views').notNull().default(0), shares: integer('shares').notNull().default(0), engagement: integer('engagement').notNull().default(0), date: timestamp('date').notNull().defaultNow() })
export const leads = pgTable('leads', { id: serial('id').primaryKey(), userId: text('userId').notNull(), name: text('name').notNull(), email: text('email').notNull(), company: text('company'), source: text('source'), score: integer('score').notNull().default(50), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const calendarEvents = pgTable('calendar_events', { id: serial('id').primaryKey(), userId: text('userId').notNull(), contentId: integer('contentId'), platform: text('platform').notNull(), scheduledTime: timestamp('scheduledTime').notNull(), published: boolean('published').notNull().default(false), createdAt: timestamp('createdAt').notNull().defaultNow() })
